### ISSUE TITLE
Issue regarding deployment guidelines

### ISSUE THREAD

**Issue by DeusCorona** [duleorlovic/tailwind_play_responsive_dark_mode#1]
An important issue that created problems with deployment via GitHub Actions is setting the permissions in workflow. By default it's set to "Read repository contents and package permissions". This should be amended to "Read and write permissions".
![image](https://user-images.githubusercontent.com/48548202/223674298-a35b94e6-3a5d-44da-9a75-1685eaf40573.png)

**Comment by duleorlovic** [comment]
Thank you for screenshot, image is better than hundred words.
I updated [README](https://github.com/duleorlovic/tailwind_play_responsive_dark_mode#github-pages)
